definitions:
  models.AuthInput:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  title: Budget Tracking App
  version: "1.0"
paths:
  /api/login:
    post:
      consumes:
      - application/json
      description: Verifies credentials and issues a JWT via HttpOnly Cookie
      parameters:
      - description: Email and Password
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.AuthInput'
      produces:
      - application/json
      responses:
        "200":
          description: Login successful
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid request body
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Incorrect password
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: User not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Database or server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Authenticate user
      tags:
      - Authentication
  /api/logout:
    post:
      description: Removes the JWT from the Cookie
      produces:
      - application/json
      responses:
        "200":
          description: Logout successful
          schema:
            additionalProperties:
              type: string
            type: object
      summary: End user session
      tags:
      - Authentication
  /api/register:
    post:
      consumes:
      - application/json
      description: Creates a new user account with the provided email and password,
        hashes the password securely, and stores the record in the PostgreSQL database.
      parameters:
      - description: User registration credentials (email and password)
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.AuthInput'
      produces:
      - application/json
      responses:
        "201":
          description: User registered successfully
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid request body
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error or email already exists
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register a new user
      tags:
      - Authentication
swagger: "2.0"
